# Sources of Environmental Variation

This book divides environmental effects up into 2 different classes:

* General environmental effects: influential factors that are shared by groups of individuals (they include maternal effects in this)
* Special environmental effects: residual deviations from the phenotype expected based on genotype and general environmental effects

## Extension of the linear model to phenotypes

Here we let $E$ and $e$ denote the contributions of general and specifc environmental effects and $I$ denote GxE. Phenotype for $k$th individual of the $i$th genotype exposed to the $j$th general environmental effect can then be described as a linear function of 4 components:

\begin{equation}
  z_{ijk} = G_{i} + I_{ij} + E_{j} + e_{ijk}
  (\#eq:phenotype-linear-model)
\end{equation}

Explaining some terms:

* $I_{ij}$, $E_{j}$, $e_{ijk}$ are defined in a least-squares sense as deviations from lower-order expectations and so have mean values equal to zero
* $\mu_{G} = \overline{z}_{ijk}$ is the mean phenotype of all genotypes in the population
* $G_i$ is the expected phenotype of the particular genotype $i$ averaged over all possible environmental conditions
* $\mu_G + E_{j}$ is the mean phenotypic value expected if all genotypes were assayed in the $j$th macroenvironment
* $G_i + I_{ij} + E_{j}$ is the expected phenotype of individuals with genotype $i$ in the $j$th macroenvironment
* $e_{ijk}$ is the deviation from that expected phenotype so, as per least-squares rules, it isn't correlated with $G_i$, $I_{ij}$ or $E_{j}$

$I$ and $e$ are uncorrelated with other variables (by construction). Remembering that the variance of a sum of uncorrelated variables is just the sum of the variances of each variable (and using equation \@ref(eq:var-of-sum)), we can define the phenotypic variance:

\begin{equation}
  \sigma^2_{P} = \sigma^2_{G} + \sigma^2_{I} + 2\sigma_{G.E} + \sigma^2_{E} + \sigma^2{e}
  (\#eq:total-phenotypic-variance)
\end{equation}

$\sigma^2_{I}$ is the GxE variance and $\sigma_{G.E}$ is the genotype-environment covariance. These terms are quite different. GxE is concerned variation in phenotypic response of specific genotypes within specific environments. Genotype-environment covariance is simply a measure of association between particular environments and genotypes. So, if individuals were randomly distributed across all environments, $\sigma_{G.E} = 0$, but $\sigma^2_{I}$ will be non-zero if genotypic and environmental effects are non-additive.

Maternal or paternal effects can cause genotype-environment covariance if there is correlation between parental genotype and ability to provision the young.

Genotype-environment covariance is often hard to estimate so and often contributes and unknown amount to estimates of genetic variance.

## Special environmental effects

Two sources: internal developmental noise and external microenvironmental heterogeneity.

### Within-individual variation

Can gain some information on within-individual variation by measuring the right and left components of a bilaterally symetrical individual. Pretty difficult to rule out external environmental contributions here though. Total variance of special environmental effects can be written as the sum of within-individual and among-individual environmental components

\begin{equation}
  \sigma^2_{e} = \sigma^2_{ew} + \sigma^2_{ea}
  (\#eq:special-environmental-effects-variance)
\end{equation}

3 types of asymmetry:

* Directional - consistent bias in one direction (e.g. heart being more to the left)
* Antisymmetry - asymmetry is the rule rather than the exception, but it is nondirectional
* Fluctuating asymmetry - the difference between left and right measures is symmetrically distributed around a mean and mode of 0

Unbiased estimate of the within-individual variance for a trait:

\begin{equation}
  \sigma^2_{ew} = \sum_{i=1}^{N} \frac{(r_i - l_i)^2}{2N} - \sigma^2_{em}
  (\#eq:within-individual-variance)
\end{equation}

$N$ is the number of individuals sampled, $r_i$ and $l_i$ are the right and left measures for the $i$th individual, and \sigma^2{em} is variance due to measurement error.

The effects of environmental stress on fluctuating asymmetry are fairly predictable - $\sigma^2_{ew}$ tends to increase in extreme or novel environments. A study suggested humans suffering from malnutrition show increases in fluctuating asymmetry.

### Developmental homeostasis and homozygosity

Lerner endorsed the idea that the degree of developmental stability is positively correlated with the overall level of individual heterozygosity. The usual mechanistic explanation is that heterozygosity acts as a buffer against environmental variation. Rest of this section discusses evidence for this hypothesis. It might be a useful exercise to think through how you'd do experiments to test the hypothesis based on the different components of variance that need to be considered. For now, here is the conclusion: "The acceptance of a general causal relationship between heterozygosity and developmental stability should be postponed until additional adequately designed experiments have been performed."

### Repeatability

Variance among repeated measures on the same individual can only be due to environmental causes (or measurement errors), so information on the within-individual component of variance can provide some insight into the possible magnitude of the environmental variance for a trait. Time complicates things (phenotypes can vary within individuals at one time and across time), but that aside, the upper-bound estimate of the genetic variance of a trait is provided by:

\begin{equation}
  \sigma^2_{G(max)} = \sigma^2_{z} - \sigma^2_{ew}
  (\#eq:genetic-variance-upper-bound)
\end{equation} 

$\sigma^2_{z}$ is an estimate for the total phenotypic variance for the trait.

Measurement error always inflates estimates of within-individual variance. As it contributes to total phenotypic variance, this cancels out in the equation above, but it's a pain because often we want to know the contribution of genetic variance to the total phenotypic variance. Repeated measures can help correct for measurement error where the measure won't change over time - e.g. adult limb length. This is less tractable for measures that vary over time as you can't distinguish variation due natural organismal changes over time and those due to measurement error.

Expected value of $\sigma^2_{G(max)}$ is greater than the total genetic variance for the trait because it includes the among-individual component of variance due to the special environmental effects ($\sigma^2_{ea}$) and variance due to general environmental effects ($\sigma^2_{E}$). Letting var(e) denote the variance associated with measurement error, the repeatablitity is:

\begin{equation}
  r = \frac{\sigma^2_{z} - \sigma^2_{ew}} {\sigma^2_{z} - \sigma^2_{em}}
  (\#eq:repeatability)
\end{equation}

and it provides an upper-bound estimate of the broad-sense heritability of a trait ($H^2$). The degree to which $r$ exceeds $H^2$ depends on the magnitude of $\sigma^2_{ea} + \sigma^2_{E}$ relative to $\sigma^2_{ew}$. If all environmental variance is just within-individual variance and no measurement error is present, then $r$ gives an unbiased estimate of $H^2$. Nice thing is that it gives an upper-bound regardless, so if $r$ is low you can say that the environmental components must dominate. Unfortunately, repeatability is often computed as the correlation between two repeated measures ($z_1$ and $z_2$) on the same individuals:

\begin{equation}
  r_F = \frac{\sigma(z_1, z_2)} {\sigma(z_1)\sigma(z_2)}
  (\#eq:falconer-repeatability)
\end{equation}

and as measurement error is contained in the denominator, it downwardly biases $r_F$. So we are no longer necessarily measuring the upper-bound of $H^2$ :(

## General environmental effects of maternal origin

Before thinking of maternal effects on offspring, remember there is little evidence for intrauterine effects on complex traits in humans, quote from GDS's twitter: "virtually all disease mother-offspring and father-offspring risk concordance the same, except maternal small excess for epilepsy (intrauterine valproate?) and type 2 diabetes" ([Link to tweet](https://twitter.com/mendel_random/status/1261221722344357889)). [Example MR paper](https://www.medrxiv.org/content/10.1101/2020.05.04.20091173v1.full).

Unless one runs an experiment where the environment of the past generation is the same as the current generation, one runs the risk that observed phenotypes are largely due to past generation. Similar thinking applies to estimates of heritability when there is assortative mating! 

There are some striking examples of maternal effects in the wild and there are plenty of associations that have been drawn between maternal age and various human traits too, for example the chances of Down's syndrome increases with maternal age. 

Lack of data for multigenerational transmission of environmental effects -- still a lack of data in 2020 in humans!

## Genotype x environment interaction

This part gives examples of experiments done to detect GxE. In the examples, it was possible to make some inference as to the existence of GxE because members of the same genetic groups were evaluated under well-defined treatments. Of course, for natural populations, assigning individuals to discrete environmental groups is often impossible, so GxE becomes unmeasurable because any GxE will be confounded with the environmental source of variance. Interestingly, I think for [Wes's GxE MR paper](https://academic.oup.com/ije/article/48/3/702/5193695), they're able to apply the method in cases without clear discrete environments. 
